# .travis.yml
dist: xenial

language: php

php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env.testing
  - sudo mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --env=testing --no-interaction -vvv

script:
  - bin/phpunit
